language: node_js
node_js:
  - 'stable'
  - 'lts/*'
  - '10'
  - '8'
script:
  - npm test
  - if [[ $TRAVIS_NODE_VERSION == "12*" ]] || [[ $TRAVIS_NODE_VERSION == "13*" ]] || [[ $TRAVIS_NODE_VERSION == stable ]]; then ./test/run.sh; fi
